group 'com.singular.sdk.flutter_sdk'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.singular.net/' }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 21
    }

    namespace 'com.singular.flutter_sdk'
}

dependencies {
    implementation 'com.singular.sdk:singular_sdk:12.16.0'
}